on:
    push:
        branches:
            - master
            - main
    pull_request:
name: Security

permissions:
  contents: read

jobs:
  Gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run Gosec
        uses: securego/gosec@0a5c6504c46569257663726ac54c7cfdad42e846 # master
        with:
          args: ./...
