on:
    push:
        branches:
            - master
            - main
    pull_request:
name: Security

permissions:
  contents: read

jobs:
  Gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run Gosec
        uses: securego/gosec@6351b0c6fcc7d75acb230a9be7f9047aada322ae # master
        with:
          args: ./...
